 image: docker:latest
 services:
  - docker:dind
 variables:
   DOCKER_DRIVER: overlay

 stages:
    - build
    - deploy

 docker-build:
     stage: build
 
     before_script:
      # Install CA certs, openssl to https downloads, python for gcloud sdk
      - apk add --update make ca-certificates openssl python
      - update-ca-certificates
      # Write our GCP service account private key into a file
      - echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      # Download and install Google Cloud SDK
      - wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz
      - tar zxvf google-cloud-sdk.tar.gz && ./google-cloud-sdk/install.sh --usage-reporting=false --path-update=true
      - google-cloud-sdk/bin/gcloud --quiet components update
      - google-cloud-sdk/bin/gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
      - docker login -u _json_key --password-stdin https://eu.gcr.io < ${HOME}/gcloud-service-key.json
     
     script:
       - docker build -t $IMAGE_NAME .
       - docker tag $IMAGE_NAME "eu.gcr.io/$GCLOUD_PROJECT_ID/$IMAGE_NAME"
       - docker push "eu.gcr.io/$GCLOUD_PROJECT_ID/$IMAGE_NAME:latest"

     only:
      refs:
        - refactor/production_ready
        - master

 deploy:
     stage: deploy
     before_script:
      - apk add --update make ca-certificates openssl python
      - update-ca-certificates
      - echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      # Download and install Google Cloud SDK
      - wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz
      - tar zxvf google-cloud-sdk.tar.gz && ./google-cloud-sdk/install.sh --usage-reporting=false --path-update=true
      - google-cloud-sdk/bin/gcloud --quiet components update
      - google-cloud-sdk/bin/gcloud components install kubectl
      - google-cloud-sdk/bin/gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
      - google-cloud-sdk/bin/gcloud container clusters get-credentials pes-eventapp-prod-cluster --zone europe-west1-b --project pes-2019-254921
     script:
       - google-cloud-sdk/bin/kubectl patch deployment pes-backend -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"build\":\"$CI_COMMIT_SHORT_SHA\"}}}}}}"
    
     only:
      refs:
        - refactor/production_ready
        - master