"""empty message

Revision ID: 270284010f7b
Revises: b708a0a0704c
Create Date: 2020-01-03 14:12:26.999685

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '270284010f7b'
down_revision = 'b708a0a0704c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Funded')

    op.create_table('funded',
                    sa.Column('event_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('fund_amount', sa.Float(), nullable=True),
                    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('event_id', 'user_id')
                    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Funded',
    sa.Column('event_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('fund_amount', mysql.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name='Funded_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='Funded_ibfk_2'),
    sa.PrimaryKeyConstraint('event_id', 'user_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('funded')
    # ### end Alembic commands ###
