"""empty message

Revision ID: 4dedfd1cc018
Revises: 2bdf9148dd07
Create Date: 2020-01-08 18:57:12.448852

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4dedfd1cc018'
down_revision = '2bdf9148dd07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votedtest',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fund_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'user_id')
    )
    op.drop_table('voted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voted',
    sa.Column('event_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('fund_amount', mysql.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name='voted_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='voted_ibfk_2'),
    sa.PrimaryKeyConstraint('event_id', 'user_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('votedtest')
    # ### end Alembic commands ###
