"""empty message

Revision ID: 6c5ac31beaed
Revises: 79f99982c97d
Create Date: 2019-11-25 15:51:12.731658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c5ac31beaed'
down_revision = '79f99982c97d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'creation_date',
               existing_type=sa.DATE(),
               type_=sa.DATETIME(),
               existing_nullable=True)
    op.alter_column('event', 'event_end_date',
               existing_type=sa.DATE(),
               type_=sa.DATETIME(),
               existing_nullable=True)
    op.alter_column('event', 'event_start_date',
               existing_type=sa.DATE(),
               type_=sa.DATETIME(),
               existing_nullable=True)
    op.alter_column('event', 'funding_end_date',
               existing_type=sa.DATE(),
               type_=sa.DATETIME(),
               existing_nullable=True)
    op.alter_column('event', 'funding_start_date',
               existing_type=sa.DATE(),
               type_=sa.DATETIME(),
               existing_nullable=True)
    op.alter_column('event', 'user_creator',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'event', 'user', ['user_creator'], ['id'])
    op.alter_column('refresh_token', 'refresh_token',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_token', 'refresh_token',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.alter_column('event', 'user_creator',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('event', 'funding_start_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('event', 'funding_end_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('event', 'event_start_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('event', 'event_end_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('event', 'creation_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
