"""empty message

Revision ID: af28242680a5
Revises: 9b7ac2140e47
Create Date: 2019-11-25 16:27:33.487689

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af28242680a5'
down_revision = '9b7ac2140e47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'creation_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('event', 'event_start_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('event', 'funding_end_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('event', 'funding_start_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('event', 'location',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=200),
               nullable=False)
    op.alter_column('event', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=200),
               nullable=False)
    op.drop_column('event', 'reports')
    op.alter_column('report', 'event_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('report', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('user', 'mail',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=200),
               nullable=False)
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=200),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.VARBINARY(length=1137),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARBINARY(length=1137),
               nullable=True)
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=200),
               nullable=True)
    op.alter_column('user', 'mail',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=200),
               nullable=True)
    op.alter_column('report', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('report', 'event_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.add_column('event', sa.Column('reports', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.alter_column('event', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=200),
               nullable=True)
    op.alter_column('event', 'location',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=200),
               nullable=True)
    op.alter_column('event', 'funding_start_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('event', 'funding_end_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('event', 'event_start_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('event', 'creation_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
