"""empty message

Revision ID: d6a5998a7cfb
Revises: 4dedfd1cc018
Create Date: 2020-01-08 19:01:46.159318

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd6a5998a7cfb'
down_revision = '4dedfd1cc018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.add_column('votedtest', sa.Column('stars', sa.Integer(), nullable=True))
    op.drop_column('votedtest', 'fund_amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votedtest', sa.Column('fund_amount', mysql.FLOAT(), nullable=True))
    op.drop_column('votedtest', 'stars')
    op.create_table('votes',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('event_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('stars', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name='votes_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='votes_ibfk_2'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
