"""empty message

Revision ID: e053ba9c5b61
Revises: 270284010f7b
Create Date: 2020-01-06 21:09:16.103514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e053ba9c5b61'
down_revision = '270284010f7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'vote', ['user_id', 'event_id'])
    op.create_foreign_key(None, 'vote', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'vote', 'event', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vote', type_='foreignkey')
    op.drop_constraint(None, 'vote', type_='foreignkey')
    op.drop_constraint(None, 'vote', type_='unique')
    op.drop_column('vote', 'id')
    # ### end Alembic commands ###
