"""empty message

Revision ID: e6749c7ef0eb
Revises: eb4d3997c874
Create Date: 2020-01-07 23:23:19.257720

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e6749c7ef0eb'
down_revision = 'eb4d3997c874'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('event', sa.Column('long', sa.Float(), nullable=True))
    op.drop_column('event', 'latitude')
    op.drop_column('event', 'longitude')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('user_id_UNIQUE', 'vote', ['user_id'], unique=True)
    op.create_index('event_id_UNIQUE', 'vote', ['event_id'], unique=True)
    op.add_column('event', sa.Column('longitude', mysql.FLOAT(), nullable=True))
    op.add_column('event', sa.Column('latitude', mysql.FLOAT(), nullable=True))
    op.drop_column('event', 'long')
    op.drop_column('event', 'lat')
    # ### end Alembic commands ###
