"""empty message

Revision ID: e6891570da15
Revises: bfae4c27cbd8
Create Date: 2020-01-02 18:21:18.748773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6891570da15'
down_revision = 'bfae4c27cbd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('event_id', sa.Integer(), nullable=False),
        sa.Column('stars', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('user_id', 'event_id')
    )
    op.add_column('event', sa.Column('stars', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'stars')
    op.drop_table('vote')
    # ### end Alembic commands ###
