"""empty message

Revision ID: eb4d3997c874
Revises: e053ba9c5b61
Create Date: 2020-01-07 23:18:42.209765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb4d3997c874'
down_revision = 'e053ba9c5b61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('event', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('user_id_UNIQUE', 'vote', ['user_id'], unique=True)
    op.create_index('event_id_UNIQUE', 'vote', ['event_id'], unique=True)
    # ### end Alembic commands ###
